### ISSUE TITLE
How to Change Font and Font Size in Awesome CV

### ISSUE THREAD

**Issue by Amarakon55** [mitchelloharawild/vitae#198]
I tried to put this in my yaml:

```yaml
mainfont: Inconsolata LGC Markup
sansfont: Inconsolata LGC Markup
monofont: Inconsolata LGC Markup
fontsize: 11pt
output:
  vitae::awesomecv:
    latex_engine: xelatex
```

But it didn't affect anything.
