### ISSUE TITLE
How to Remove Bottom Text?

### ISSUE THREAD

**Issue by Amarakon55** [mitchelloharawild/vitae#200]
When I export to PDF using awesomecv, it shows this at the bottom:\
*NAME* · CURRICULUM VITAE

I don't want it to show that.

**Comment by shirdekel** [comment]
I have a pull request (https://github.com/mitchelloharawild/vitae/pull/182) that does this. Have a look at the commit or my fork to implement.

**Comment by mitchelloharawild** [comment]
Thanks to you both. I've added a `show_footer` option for awesomecv. To remove the footer, you would write:

```yaml
output: 
  vitae::awesomecv:
    show_footer: false
```
