### ISSUE TITLE
do not support unicode

### ISSUE THREAD

**Issue by sin-33** [mitchelloharawild/vitae#201]
Thank you for your excellent package to make a cv.

When I want to write my cv in Chinese, the pdf cannot show right words. Could you please give me a solution ?

**Comment by mitchelloharawild** [comment]
Could you provide a minimal reproducible example? It should be possible to write a CV which Chinese unicode characters.
You might need to use xelatex, which can be done with:
```yaml
output: 
  vitae::awesomecv:
    latex_engine: xelatex
```
