### ISSUE TITLE
Issue with Orcid removal

### ISSUE THREAD

**Issue by TulaniansWERC** [mitchelloharawild/vitae#243]
Hello, 

I am running into and issue when knitting awesomecv without the Orcid icon and information in the yaml header.  This is my current Yaml header.  
```
---
name: YYYYY
surname: YYYYYYY
headcolor: 414141
#profilepic: "C:/Users/YYY/Box/CV_Resume/YYYYY_Headshots_2022/PHOTO.jpg"
#qualifications: 
position: "Doctor in Medicine"
address: "ADDRESS"
phone: "NUMBERS"
email: "EMAIL"
#orcid: 0000.0000.0000.0000
date: '`r format(Sys.Date(), "%B %d, %Y")`'
csl: "csl/apa6-cv.csl"
nocite: "@*"
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyhead[R]{\thepage}
  - \usepackage{float}
  - \usepackage{multicol}
  - \usepackage{colortbl}
  - \arrayrulecolor{white}
  - \usepackage{hhline}
  - \definecolor{light-gray}{gray}{0.95}
  - \apptocmd{\tightlist}{\setlength{\itemsep}{2pt}}{}{}
output:
  vitae::awesomecv:
    page_total: true
    fig_caption: yes
    keep_tex: yes
    pandoc_args: 
     #- --lua-filter="lua/strong_sur.lua"
     #- --lua-filter="lua/emph.lua"
     #- --lua-filter="lua/highlight-author.lua"
      
engine: pdflatex
--- 

```

Eliminating and muting the Orcid returns the following error:  ! LaTeX Error: There's no line here to end.
Error: LaTeX failed to compile

Any ideas on what might be happening?
